#:schema node_modules/wrangler/config-schema.json
name = "jedbillyb-com"
type = "javascript"
account_id = ""
workers_dev = true
main = "dist/index.html"

[site]
bucket = "./dist"

[build]
command = "npm run build"
cwd = "./"

